name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      go-fdo-server-branch:
        description: Go FDO server branch
        default: main
        required: true
  push:
    branches:
      - main
  pull_request:

jobs:
  test-makefile:
    name: build and test makefile
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build and install the binary
        run: |
           make && sudo install -D -m 755 go-fdo-client /usr/bin/

      - name: Fail if the source code has changes after build
        uses: NathanielHill/fail-if-changes@master

      - name: Generate certs
        run: |
          source .github/scripts/fdo-utils.sh
          generate_certs

      - name: Build and spawn FDO server containers
        id: build-and-run-servers
        uses: hoverkraft-tech/compose-action@v2.3.0
        with:
          compose-file: ".github/compose/servers.yaml"
          services-log-level: debug
          up-flags: "--build"
        env:
          GO_FDO_SERVER_FLAGS: ${{inputs.go-fdo-server-branch}}

      - name: Test FIDO Device Onboarding
        run: |
          source .github/scripts/fdo-utils.sh
          test_onboarding

      - name: Get Manufacturer, Rendezvous and Owner server logs
        run: |
          source .github/scripts/fdo-utils.sh
          get_server_logs

  test-container:
    name: build and test containers
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build the client container
        run: |
          docker build -t go-fdo-client .

      - name: Fail if the source code has changes after build
        uses: NathanielHill/fail-if-changes@master

      - name: Generate certs
        run: |
          source .github/scripts/fdo-utils.sh
          generate_certs

      - name: Build and spawn FDO server containers
        id: build-and-run-servers
        uses: hoverkraft-tech/compose-action@v2.3.0
        with:
          compose-file: ".github/compose/servers.yaml"
          services-log-level: debug
          up-flags: "--build"
        env:
          GO_FDO_SERVER_FLAGS: ${{inputs.go-fdo-server-branch}}

      - name: Test FIDO Device Onboarding
        run: |
          source .github/scripts/container-utils.sh
          test_onboarding

      - name: Get Manufacturer, Rendezvous and Owner server logs
        run: |
          source .github/scripts/container-utils.sh
          get_server_logs

  test-native:
    name: "Native: ${{ matrix.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - test: test-onboarding
            name: Test FIDO device onboarding
          - test: test-onboarding-config
            name: Test FIDO device onboarding using a configuration file
          - test: test-onboarding-v2
            name: Test FIDO device onboarding (V2 API)
          - test: test-ov-verification
            name: Test Ownership Voucher verification
          - test: test-resale
            name: Test FIDO resale protocol
          - test: test-fsim-wget
            name: Test FSIM fdo.wget
          - test: test-fsim-upload
            name: Test FSIM fdo.upload
          - test: test-fsim-download
            name: Test FSIM fdo.download
          - test: test-fsim-command
            name: Test FSIM fdo.command
          - test: test-fsim-config
            name: Test a sequence of FSIM operations using a configuration file
          - test: test-device-ca-api
            name: Test Device CA API
          - test: test-device-ca-rendezvous-trust
            name: Test Device CA rendezvous trust verification
          - test: test-rv-bypass
            name: Test RV bypass
          - test: test-rv-bypass-v2
            name: Test RV bypass (V2 API)
          - test: test-rvinfo-apis-v2
            name: Test RVInfo API Lifecycle (V2 API)
    env:
      CLIENT_LOCAL_PATH: ${{ github.workspace }}
      SERVER_LOCAL_PATH: ${{ github.workspace }}/server
    steps:
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check out go-fdo-server
        uses: actions/checkout@v4
        with:
          repository: fido-device-onboard/go-fdo-server
          ref: ${{ inputs.go-fdo-server-branch || 'main' }}
          path: server

      - name: Check out go-fdo-ci
        uses: actions/checkout@v4
        with:
          repository: fido-device-onboard/go-fdo-ci
          path: ci

      - name: ${{ matrix.name }}
        run: |
          source ci/test/ci/${{ matrix.test }}.sh
          run_test

      - name: Get Manufacturer, Rendezvous and Owner server logs
        if: always()
        run: |
          source ci/test/ci/${{ matrix.test }}.sh
          get_logs

      - name: Cleanup the environment
        if: always()
        run: |
          source ci/test/ci/${{ matrix.test }}.sh
          cleanup
